### ISSUE TITLE
Strange menu rendering

### ISSUE THREAD

**Issue by aguadotzn** [artemsheludko/derrick#1]
Hi Artem. I was just taking a look to the theme. 

- First, thanks for the fantastic theme. 

- Second, I notice in the site the following style issue when changing into collapsible/ non-collapsible menu

![MenuShadow](https://user-images.githubusercontent.com/22575055/80948709-f7f74180-8df2-11ea-8f06-fb9f60b188e3.gif)

What should be the reason for this? Any Idea on how to fix it?

Thanks in advance

**Comment by artemsheludko** [comment]
Hi Adrián,

For users of various devices, it will be imperceptible. Since this happens only during the resizing of the browser, and not during the rendering of the page.

But you can change this by adding opacity to the transition property (transition: opacity 400ms ease-in-out;)

![Screen Shot 2020-05-05 at 11 02 51 AM](https://user-images.githubusercontent.com/22279513/81046457-19266380-8ec1-11ea-95ca-d7e6a57b8f44.png)

**Comment by aguadotzn** [comment]
Super! Thanks for the feedback !

**Comment by artemsheludko** [comment]
@aguadotzn 
You're welcome!!!
